import gsap from 'gsap/gsap-core'
import React from 'react'

export default class Home extends React.Component {




    componentDidMount(){
gsap.from('.home',{display:'none',delay:6})
    }
    render(){

    return (
        <div className='section home'>
                <h1 className='sec-title'>HOME</h1>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
                <p className='content'>export default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Componentexport default class Sections extends React.Component</p>
        </div>
    )
}
}